- name: sonarqube
  hosts: all
  tasks:
    - name: sonarqube test
      command: echo "SUCCESS"
      register: output
    - command: echo "SonarQube tests OK"
      when: output.stdout.find('SUCCESS') != -1  
    - fail:
      msg: "SonarQube tests failed"
      when: output.stdout.find('SUCCESS') == -1 
