- name: sonarqube
  hosts: all
  tasks:
    - name: sonarqube test
      command: echo "SUCCESS"
      register: output
    - name: check test
      command: echo "SonarQube tests OK"
      when: output.stdout.find('SUCCESS') != -1  
    - name: check output
      fail:
        msg: "SonarQube tests failed"
      when: output.stdout.find('SUCCESS') == -1 
