- name: taurus
  hosts: all
  tasks:
    - name: taurus test
      command: echo "SUCCESS"
      register: output
    - name: check test
      command: echo "Taurus tests OK"
      when: output.stdout.find('SUCCESS') != -1  
    - name: check output
      fail:
        msg: "Taurus tests failed"
      when: output.stdout.find('SUCCESS') == -1 
